global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['host.docker.internal:8001','ai.salesninjacrm.com','aiservice.salesninjacrm.com']
